#!/usr/bin/env python3
"""Expand an orbit description (benchmark_path_*.json) into a flat trajectory
file the IPU server can play back via --play-path.

Output format (plain text, one statement per line):
    # comments start with #
    fov_half_rad: 0.524
    ply: data/pringles.ply
    v <16 floats>   <-- GLM column-major view matrix in COLMAP convention
    v <16 floats>
    ...

Each "v" line is one frame of camera pose. The server iterates these poses,
one per rendered frame, and loops back to 0 at the end.
"""

import argparse
import json
import os
import sys
import numpy as np


def look_at_colmap(eye, target, world_up):
    """Build a 4x4 COLMAP view matrix by exactly mirroring what splat.cpp does:
    build a standard OpenGL view (gluLookAt-style), then apply the
    OpenGL -> COLMAP row flip (diag(1, -1, -1, 1)).

    `world_up` is the world direction the scene treats as "up" (i.e. should
    appear at the top of the rendered image). For this project with
    --flip-scene that's typically (0, -1, 0).
    """
    f = target - eye
    nf = np.linalg.norm(f)
    if nf < 1e-9:
        raise ValueError("eye and target are coincident")
    f = f / nf

    # OpenGL gluLookAt convention: camera looks down -Z, view +Y = world_up.
    s = np.cross(f, world_up)
    ns = np.linalg.norm(s)
    if ns < 1e-9:
        raise ValueError("forward is parallel to world_up; pick a different up axis")
    s = s / ns
    u = np.cross(s, f)

    R_gl = np.stack([s, u, -f], axis=0)
    t_gl = -R_gl @ eye

    # OpenGL -> COLMAP: pre-multiply by diag(1, -1, -1, 1). Negates rows 1, 2.
    R_colmap = np.array([R_gl[0], -R_gl[1], -R_gl[2]])
    t_colmap = np.array([t_gl[0], -t_gl[1], -t_gl[2]])

    M = np.eye(4)
    M[:3, :3] = R_colmap
    M[:3, 3] = t_colmap
    return M


def M_to_glm_flat(M):
    """Mathematical row-major M (4x4) -> GLM column-major flat list of 16."""
    return M.T.reshape(-1).tolist()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('orbit_json', help='Orbit description (benchmark_path_*.json)')
    ap.add_argument('--out', required=True, help='Output trajectory file (.traj)')
    ap.add_argument('--frames', type=int, default=360, help='Number of poses (default 360)')
    ap.add_argument('--span-deg', type=float, default=360.0,
                    help='Total angle to sweep, in degrees (default 360 = full loop)')
    ap.add_argument('--start-azimuth-deg', type=float, default=None,
                    help='Starting azimuth in degrees (default: anchor A azimuth)')
    ap.add_argument('--reverse', action='store_true',
                    help='Reverse rotation direction')
    args = ap.parse_args()

    with open(args.orbit_json) as f:
        orbit = json.load(f)

    look_at = np.array(orbit['look_at'], dtype=np.float64)
    axis = np.array(orbit['axis'], dtype=np.float64)
    world_up = np.array(orbit['world_up'], dtype=np.float64)
    camera_y = float(orbit['camera_y'])
    radius = float(orbit['radius'])
    fov_half = float(orbit['fov_half_rad'])
    direction = int(orbit.get('rotation_direction', -1))
    if args.reverse:
        direction = -direction

    if not np.allclose(axis, [0.0, 1.0, 0.0]):
        print("warning: this script currently assumes axis = +Y; output may be wrong otherwise",
              file=sys.stderr)

    az_start = (args.start_azimuth_deg
                if args.start_azimuth_deg is not None
                else float(orbit['anchor_a']['azimuth_deg']))
    span = direction * abs(args.span_deg)

    lines = []
    lines.append(f"# generated by tools/sample_orbit_path.py")
    lines.append(f"# orbit_json: {os.path.relpath(args.orbit_json)}")
    lines.append(f"# frames: {args.frames}  span_deg: {span:+.3f}  az_start: {az_start:.3f}")
    if 'notes' in orbit:
        lines.append(f"# notes: {orbit['notes']}")
    lines.append(f"fov_half_rad: {fov_half}")
    if orbit.get('ply'):
        lines.append(f"ply: {orbit['ply']}")

    n = args.frames
    for i in range(n):
        t = i / float(n)
        az = np.radians(az_start + span * t)
        # Camera orbits a vertical line through look_at, at fixed Y = camera_y.
        # azimuth atan2(z, x) so eye = look_at.xz + (r cos, r sin).
        eye = np.array([look_at[0] + radius * np.cos(az),
                        camera_y,
                        look_at[2] + radius * np.sin(az)])
        M = look_at_colmap(eye, look_at, world_up)
        flat = M_to_glm_flat(M)
        lines.append("v " + " ".join(f"{x:.7g}" for x in flat))

    with open(args.out, 'w') as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {n} poses to {args.out} ({span:+.2f} deg sweep from az={az_start:.2f})")


if __name__ == '__main__':
    main()
