#!/usr/bin/env python3
"""Generate a 'teleport' trajectory for measuring data-locality cost.

Picks N random azimuths on the orbit (same look_at / radius / camera_y as
the orbit JSON), and writes each pose K times in a row. Per-block analysis
of the bench CSV then shows the settling curve: frame 0 after each teleport
is the worst case (channels fully scrambled), frame K-1 should approach
static-pose ms once locality is fully exploited.

Output schema is identical to sample_orbit_path.py so the same playback +
benchmark code paths work unchanged.
"""

import argparse
import json
import os
import random
import sys

import numpy as np

# Reuse helpers from sample_orbit_path.py (same dir)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sample_orbit_path import look_at_colmap, M_to_glm_flat   # noqa: E402


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('orbit_json', help='Orbit description (benchmark_path_*.json)')
    ap.add_argument('--out', required=True, help='Output trajectory file (.traj)')
    ap.add_argument('--num-poses', type=int, default=40,
                    help='Number of distinct random camera positions (default 40)')
    ap.add_argument('--hold-frames', type=int, default=30,
                    help='Hold each pose for this many frames (default 30)')
    ap.add_argument('--seed', type=int, default=42,
                    help='Random seed for reproducibility (default 42)')
    args = ap.parse_args()

    with open(args.orbit_json) as f:
        orbit = json.load(f)

    look_at = np.array(orbit['look_at'], dtype=np.float64)
    axis = np.array(orbit['axis'], dtype=np.float64)
    world_up = np.array(orbit['world_up'], dtype=np.float64)
    radius = float(orbit['radius'])
    camera_y = float(orbit['camera_y'])
    fov_half = float(orbit['fov_half_rad'])

    if not np.allclose(axis, [0.0, 1.0, 0.0]):
        print("warning: this script assumes axis = +Y", file=sys.stderr)

    rng = random.Random(args.seed)
    azimuths_deg = [rng.uniform(-180.0, 180.0) for _ in range(args.num_poses)]

    lines = [
        f"# generated by tools/sample_teleport_path.py",
        f"# orbit_json: {os.path.relpath(args.orbit_json)}",
        f"# num_poses: {args.num_poses}  hold_frames: {args.hold_frames}  seed: {args.seed}",
        f"# total frames: {args.num_poses * args.hold_frames}",
        f"# azimuths_deg: {[round(a, 2) for a in azimuths_deg]}",
        f"fov_half_rad: {fov_half}",
    ]
    if orbit.get('ply'):
        lines.append(f"ply: {orbit['ply']}")

    for az_deg in azimuths_deg:
        az = np.radians(az_deg)
        eye = np.array([
            look_at[0] + radius * np.cos(az),
            camera_y,
            look_at[2] + radius * np.sin(az),
        ])
        M = look_at_colmap(eye, look_at, world_up)
        flat = M_to_glm_flat(M)
        v_line = "v " + " ".join(f"{x:.7g}" for x in flat)
        for _ in range(args.hold_frames):
            lines.append(v_line)

    with open(args.out, 'w') as f:
        f.write("\n".join(lines) + "\n")
    total = args.num_poses * args.hold_frames
    print(f"wrote {total} frames ({args.num_poses} teleports x {args.hold_frames} held) to {args.out}")


if __name__ == '__main__':
    main()
